export const questions = [
    "I look for things that need to be done",
    "When faced with a difficult problem, I spend a lot of time trying to find a solution",
    "I complete my work on time",
    "It bothers me when things are not done very well.",
    "I prefer situations in which I can control the outcomes as much as possible",
    "When starting a new task or project, I gather a great deal of information before going ahead",
    "I get others to support my recommendations",
    "I feel confident that I will succeed at whatever I try to do",
    "No matter whom I'm talking to, I'm a good listener",
    "I do things that need to be done before being asked to do so by others",
    "I try several times to get people to do what I would like them to do",
    "I keep the promise I make",
    "My own work is better than that of other people I work with",
    "I don't try something new without making sure I will succeed",
    "I seek the advice of people who know a lot about the tasks I'm working on",
    "I do not spend much time thinking about how to influence others",
    "I change my mind if others disagree strongly with me",
    "I feel resentful when I don't get my way",
    "I like challenges and new opportunities",
    "When something gets in the way of what I'm trying to do, I keep on trying to accomplish what I want",
    "I am happy to do someone else's work if necessary to get the job done on time",
    "It bothers me when my time is wasted",
    "I weigh my chances of succeeding or failing before I decide to do something",
    "I take action without wasting time gathering information.",
    "I get important people to help me accomplish my goals",
    "When trying something difficult or challenging, I feel confident that I will succeed",
    "In the past I have had failures",
    "I prefer activities that I know well and with which I am comfortable",
    "When faced with major difficulties, I quickly go on to other things",
    "When I'm doing a job for someone, I make a special effort to make sure that the person is happy with my work.",
    "I'm never entirely happy with the way in which things are done; I always think there must be a better way",
    "I do things that are risky",
    "When working for a project for someone, I ask many questions to be sure I understand what the person wants.",
    "In order to reach my goals, I think of solutions that benefit everyone involved in the problem.",
    "I do very good work",
    "There have been occasions when I took advantage of someone",
    "I try things that are very new and different from what I have done before",
    "I try several ways to overcome things that get in the way of reaching my goals",
    "My family and personal life are more important to me than work deadlines I set for myself",
    "I do not find ways to complete tasks faster at work and at home",
    "I do things that others consider risky",
    "I go to several different sources to get information to help with tasks or projects",
    "I am able to get people who have strong opinions or ideas to change their minds",
    "I stick with my decisions even if others disagree strongly with me",
    "When I don't know something, I don't mind admitting it"
];

export const categories = [
    "A: Seeking Opportunities", "B: Persistence", "C: Commitment to work",
    "D: Quality & Creativity", "E: Risk taking", "F: Goal setting",
    "G: Persuasion & Networking", "H: Self-confidence"
];
