export type Language = "en" | "ta" | "si";

export const questions: Record<Language, string[]> = {
  en: [
    "I look for things that need to be done",
    "When faced with a difficult problem, I spend a lot of time trying to find a solution",
    "I complete my work on time",
    "It bothers me when things are not done very well.",
    "I prefer situations in which I can control the outcomes as much as possible",
    "When starting a new task or project, I gather a great deal of information before going ahead",
    "I get others to support my recommendations",
    "I feel confident that I will succeed at whatever I try to do",
    "No matter whom I'm talking to, I'm a good listener",
    "I do things that need to be done before being asked to do so by others",
    "I try several times to get people to do what I would like them to do",
    "I keep the promise I make",
    "My own work is better than that of other people I work with",
    "I don't try something new without making sure I will succeed",
    "I seek the advice of people who know a lot about the tasks I'm working on",
    "I do not spend much time thinking about how to influence others",
    "I change my mind if others disagree strongly with me",
    "I feel resentful when I don't get my way",
    "I like challenges and new opportunities",
    "When something gets in the way of what I'm trying to do, I keep on trying to accomplish what I want",
    "I am happy to do someone else's work if necessary to get the job done on time",
    "It bothers me when my time is wasted",
    "I weigh my chances of succeeding or failing before I decide to do something",
    "I take action without wasting time gathering information.",
    "I get important people to help me accomplish my goals",
    "When trying something difficult or challenging, I feel confident that I will succeed",
    "In the past I have had failures",
    "I prefer activities that I know well and with which I am comfortable",
    "When faced with major difficulties, I quickly go on to other things",
    "When I'm doing a job for someone, I make a special effort to make sure that the person is happy with my work.",
    "I'm never entirely happy with the way in which things are done; I always think there must be a better way",
    "I do things that are risky",
    "When working for a project for someone, I ask many questions to be sure I understand what the person wants.",
    "In order to reach my goals, I think of solutions that benefit everyone involved in the problem.",
    "I do very good work",
    "There have been occasions when I took advantage of someone",
    "I try things that are very new and different from what I have done before",
    "I try several ways to overcome things that get in the way of reaching my goals",
    "My family and personal life are more important to me than work deadlines I set for myself",
    "I do not find ways to complete tasks faster at work and at home",
    "I do things that others consider risky",
    "I go to several different sources to get information to help with tasks or projects",
    "I am able to get people who have strong opinions or ideas to change their minds",
    "I stick with my decisions even if others disagree strongly with me",
    "When I don't know something, I don't mind admitting it",
  ],

  ta: [
    "செய்யப்பட வேண்டிய விஷயங்களை நான் தேடுகிறேன்",
    "கடினமான சிக்கலை எதிர்கொள்ளும்போது, தீர்வு கண்டுபிடிக்க நான் நிறைய நேரம் செலவிடுகிறேன்",
    "என் வேலையை நேரத்தில் முடிக்கிறேன்",
    "விஷயங்கள் சரியாக செய்யப்படாதபோது என்னை தொந்தரவு செய்கிறது.",
    "முடிவுகளை எனக்கு முடிந்தவரை கட்டுப்படுத்தக்கூடிய சூழல்களை விரும்புகிறேன்",
    "புதிய பணி அல்லது திட்டத்தை தொடங்கும்போது, முன்னேறுவதற்கு முன் நான் நிறைய தகவல்களை சேகரிக்கிறேன்",
    "என் பரிந்துரைகளை ஆதரிக்க மற்றவர்களை வைக்கிறேன்",
    "நான் என்ன செய்ய முயற்சித்தாலும் வெற்றி பெறுவேன் என்று நம்பிக்கை உணர்கிறேன்",
    "யாரிடம் பேசினாலும், நான் நல்ல கேட்பவன்",
    "மற்றவர்கள் கேட்கும் முன்பே செய்யப்பட வேண்டிய விஷயங்களை நான் செய்கிறேன்",
    "மக்கள் என்ன செய்யவேண்டும் என்று நான் விரும்புகிறேனோ அதை செய்யவைக்க பலமுறை முயற்சிக்கிறேன்",
    "நான் செய்த வாக்குறுதிகளை காப்பாற்றுகிறேன்",
    "என்னுடன் பணிபுரிபவர்களை விட என் வேலை சிறந்தது",
    "வெற்றி பெறுவேன் என்று உறுதியாக தெரியாமல் புதியதை முயற்சிக்க மாட்டேன்",
    "நான் பணிபுரியும் பணிகள் பற்றி அதிகம் தெரிந்தவர்களின் ஆலோசனையை நாடுகிறேன்",
    "மற்றவர்களை எவ்வாறு பாதிப்பது என்று சிந்திக்க அதிக நேரம் செலவிட மாட்டேன்",
    "மற்றவர்கள் என்னோடு கடுமையாக கருத்து மாறுபட்டால் என் மனதை மாற்றிக்கொள்கிறேன்",
    "என் விருப்பப்படி நடக்காதபோது வருத்தமாக உணர்கிறேன்",
    "சவால்களையும் புதிய வாய்ப்புகளையும் விரும்புகிறேன்",
    "நான் செய்ய முயற்சிப்பதில் ஏதாவது தடையாக வரும்போது, நான் விரும்புவதை அடைய தொடர்ந்து முயற்சிக்கிறேன்",
    "வேலையை நேரத்தில் முடிக்க தேவைப்பட்டால் மற்றொருவரின் வேலையை செய்ய மகிழ்ச்சியாக இருக்கிறேன்",
    "என் நேரம் வீணாகும்போது என்னை தொந்தரவு செய்கிறது",
    "ஏதாவது செய்ய முடிவெடுப்பதற்கு முன் வெற்றி அல்லது தோல்வியின் வாய்ப்புகளை எடைபோடுகிறேன்",
    "தகவல் சேகரிக்க நேரம் வீணாக்காமல் நடவடிக்கை எடுக்கிறேன்.",
    "என் இலக்குகளை அடைய முக்கியமான நபர்களை உதவ வைக்கிறேன்",
    "கடினமான அல்லது சவாலான ஒன்றை முயற்சிக்கும்போது, வெற்றி பெறுவேன் என்று நம்பிக்கை உணர்கிறேன்",
    "கடந்த காலத்தில் தோல்விகளை அனுபவித்திருக்கிறேன்",
    "நான் நன்கு அறிந்த மற்றும் வசதியான செயல்களை விரும்புகிறேன்",
    "பெரிய சிரமங்களை எதிர்கொள்ளும்போது, விரைவில் மற்ற விஷயங்களுக்கு சென்றுவிடுகிறேன்",
    "யாருக்காக வேலை செய்யும்போது, அந்த நபர் என் வேலையில் மகிழ்ச்சியாக இருக்கிறார் என்று உறுதிப்படுத்த சிறப்பு முயற்சி செய்கிறேன்.",
    "விஷயங்கள் செய்யப்படும் விதத்தில் நான் முழுமையாக மகிழ்ச்சியாக இல்லை; எப்போதும் ஒரு சிறந்த வழி இருக்கும் என்று நினைக்கிறேன்",
    "ஆபத்தான விஷயங்களை செய்கிறேன்",
    "யாருக்காவது திட்டம் செய்யும்போது, அந்த நபர் என்ன விரும்புகிறார் என்று புரிந்துகொள்ள நிறைய கேள்விகள் கேட்கிறேன்.",
    "என் இலக்குகளை அடைய, சிக்கலில் ஈடுபட்ட அனைவருக்கும் பயனளிக்கும் தீர்வுகளை சிந்திக்கிறேன்.",
    "மிகவும் சிறந்த வேலை செய்கிறேன்",
    "யாரையாவது சுரண்டிய சந்தர்ப்பங்கள் இருந்தன",
    "முன்பு செய்தவற்றிலிருந்து மிகவும் புதியதும் வித்தியாசமானதுமான விஷயங்களை முயற்சிக்கிறேன்",
    "என் இலக்குகளை அடைவதில் தடையாக வரும் விஷயங்களை கடக்க பல வழிகளை முயற்சிக்கிறேன்",
    "என் குடும்பமும் தனிப்பட்ட வாழ்க்கையும் நான் அமைத்துக்கொண்ட வேலை காலக்கெடுவை விட முக்கியமானது",
    "வேலையிலும் வீட்டிலும் பணிகளை விரைவாக முடிக்க வழிகளை கண்டறிவதில்லை",
    "மற்றவர்கள் ஆபத்தானதாக கருதும் விஷயங்களை செய்கிறேன்",
    "பணிகள் அல்லது திட்டங்களுக்கு உதவ தகவல் பெற பல்வேறு ஆதாரங்களை அணுகுகிறேன்",
    "வலுவான கருத்துக்கள் அல்லது கருத்துகள் உள்ளவர்களை மனம் மாற்ற வைக்கும் திறன் என்னிடம் உள்ளது",
    "மற்றவர்கள் கடுமையாக கருத்து மாறுபட்டாலும் என் முடிவுகளில் உறுதியாக இருக்கிறேன்",
    "ஏதாவது தெரியாதபோது, அதை ஒப்புக்கொள்வதில் கவலையில்லை",
  ],

  si: [
    "මම මා විසින් කලයුතු වැඩ ගැන සොයා බලමි",
    "මට අසීරු ගැටළුවකට මුහුනපා ඇති විට ඒ සඳහා විසඳුමක් සොයා ගැනීමට බොහෝ කාලය ගත කරමි",
    "මම මගේ වැඩ නියමිත වෙලාවට අවසන් කරමි",
    "අවශ්‍ය දේ නිවැරදිව සිදු නොවන අවස්ථා වලදී මම අපහසුතාවයට පත් වෙමි.",
    "මට පාලනය කළ හැකි ප්‍රතිඵල ලබා ගැනීමට මම වඩාත් ප්‍රිය කරමි",
    "මට අලුළුත් ඉලක්කයකට යාමට ඇති විට එම ගමන ආරම්භ කිරීමට පෙර බොහෝ තොරතුරු සොයම්",
    "මම මගේ නිර්දේශ තහවුරු කිරීම සඳහා අන් අයගේ සහය ගනිමි",
    "මම කුමක් කරන්නට උත්සහ කලත් එය සාර්ථකවේය යන විශ්වාසය මට ඇත",
    "මා තවුරුන් සමග කතා කලත් මම හොද සවන්දෙන්නෙක් වෙමි",
    "අන් අය ඉල්ලීමට පෙරම කළ යුතු දේ කරමි",
    "මා කිරීමට කැමති දේ කිරීමට ජනයා ලබා ගැනීමට කිහිප වතාවක් උත්සාහ කරමි",
    "කළ පොරොන්දු ඉටු කරමි",
    "මා සමඟ වැඩ කරන අනෙකුත් අයගේ වැඩට වඩා මගේ වැඩ හොඳය",
    "සාර්ථක වෙනවා යැයි නිශ්චිත නොවී නව දෙයක් උත්සාහ නොකරමි",
    "මා කරන කාර්යයන් ගැන දන්නා අයගේ උපදෙස් ලබා ගනිමි",
    "අන් අයට බලපෑම් කරන ආකාරය ගැන කල්පනා කිරීමට වැඩි කාලයක් ගත නොකරමි",
    "අන් අය දැඩි ලෙස දෙකඩ වූ විට මගේ මතය වෙනස් කරමි",
    "මගේ ආකාරයට නොයන විට රිසිය නොදැනෙමි",
    "අභියෝග සහ නව අවස්ථා කැමතිය",
    "කිරීමට යන දෙයකට බාධා ඇති වූ විට, කිරීමට කැමති දේ ඉටු කිරීමට දිගටම උත්සාහ කරමි",
    "කාර්යය කාලයට ඉටු කිරීමට අවශ්‍ය නම් වෙනත් කෙනෙකුගේ වැඩ කිරීමට සතුටු වෙමි",
    "මගේ කාලය නාස්ති වන විට කරදරයකි",
    "යමක් කිරීමට තීරණය කිරීමට පෙර සාර්ථකත්වය හෝ අසාර්ථකත්වය ගැන සිතා බලමි",
    "තොරතුරු රැස් කිරීමට කාලය නාස්ති නොකර ක්‍රියාත්මක වෙමි.",
    "ඉලක්ක සාක්ෂාත් කිරීමට වැදගත් අය ලබා ගනිමි",
    "දුෂ්කර හෝ අභියෝගාත්මක දෙයක් කරන විට, සාර්ථක වෙනවා යැයි විශ්වාස කරමි",
    "අතීතයේ අසාර්ථකත්වයන් ලබා ඇත",
    "හොඳින් දන්නා සහ සුවපහසු ක්‍රියාකාරකම් කැමතිය",
    "ප්‍රධාන දුෂ්කරතාවන්ට මුහුණ දෙන විට, ඉක්මනින් වෙනත් දේවලට යයි",
    "යමෙකු වෙනුවෙන් කාර්යයක් කරන විට, ඒ පුද්ගලයා මගේ වැඩ ගැන සතුටු බව නිශ්චිත කිරීමට විශේෂ උත්සාහයක් ගනිමි.",
    "දේවල් කරනු ලබන ආකාරයෙන් කිසිදා සම්පූර්ණයෙන් සතුටු නොවෙමි; සෑම විටම වඩා හොඳ ක්‍රමයක් ඇති බව සිතමි",
    "අවදානම් දේ කරමි",
    "යමෙකු වෙනුවෙන් ව්‍යාපෘතියක් කරන විට, ඒ පුද්ගලයා කැමති දේ තේරුම් ගැනීමට ප්‍රශ්න බොහොමයක් අසමි.",
    "මගේ අරමුණ කරා යාමේදී ඒ සඳහා සම්බන්ධ වන සියලු දෙනාගේ ගැටළු වලට විසඳුම් ගැන සිතමි.",
    "මම සැමවිටම ඉතාමත් කැපවීමෙන් හා කාර්යක්ෂමව කටයුතු කරමි",
    "සමහර අවස්ථාවලදී අන් අය මගේ වාසියට හරවා ගන්නා අවස්ථා පවතී.",
    "මම මෙතෙක් නොකළ හා නවතම කාර්යයන් කිරීමට උත්සාහ ගනිමි.",
    "මගේ අරමුණ කරා යාමේදී ඇතිවන තත්වයන්ට මුහුණදීම විවිධ මාර්ග ඔස්සේ උත්සාහ කරමි.",
    "මට රාජ්‍ය මට්ටමේ ඉලක්ක වලට වඩා පවුලේ හා පුද්ගලික ජීවිතය වැදගත් යැයි සිතේ",
    "මම වැඩපළේද නිවසේදීද ඉලක්ක ඉක්මනින් අවසන් කිරීම සඳහා ක්‍රමවේද සොයමී.",
    "අන් අය අවදානම් සහිත යයි සලකන වැඩ මම කරමි",
    "ඉලක්ක හා ව්‍යාපෘති වලට සහය වීම සඳහා මම බොහෝ තොරතුරු මුලාශ්‍ර වෙත යොමු වෙයි",
    "තමන්ගේ අදහස් වල ඉතා දැඩිව එල්බගෙන ඉන්නා අයගේ මනස වෙනස් කිරීමට මට හැකියාව ඇත",
    "කවුරුන් ප්‍රභල ලෙස විරුද්ධ වුවත් මම මගේ තීරණයේ සෘජුව සිටීම",
    "මම යම් දෙයක් ගැන නොදන්නේ නම් ඒ ගැන කීමට අතමැත්තක් නැත",
  ],
};

export const categories: Record<Language, string[]> = {
  en: [
    "A: Seeking Opportunities", "B: Persistence", "C: Commitment to work",
    "D: Quality & Creativity", "E: Risk taking", "F: Goal setting",
    "G: Persuasion & Networking", "H: Self-confidence",
  ],
  ta: [
    "A: வாய்ப்புகளை தேடுதல்", "B: விடாமுயற்சி", "C: வேலையில் அர்ப்பணிப்பு",
    "D: தரம் & படைப்பாற்றல்", "E: ஆபத்தை ஏற்றல்", "F: இலக்கு நிர்ணயம்",
    "G: வற்புறுத்தல் & வலைப்பின்னல்", "H: தன்னம்பிக்கை",
  ],
  si: [
    "A: අවස්ථා සෙවීම", "B: දිගටම ඉදිරියට යාම", "C: කාර්ය කැපවීම",
    "D: ගුණාත්මකභාවය & නිර්මාණශීලිත්වය", "E: අවදානම් ගැනීම", "F: ඉලක්ක සැකසීම",
    "G: ඒකාබද්ධ කිරීම & ජාලකරණය", "H: ආත්ම විශ්වාසය",
  ],
};
